{% set version = "0.9.0" %}

package:
  name: tensorflow
  version: {{ version }}

source:
  git_url: https://github.com/tensorflow/tensorflow
  git_tag: v{{ version }}
  patches:
    - 0001-conda-Change-lib64-to-lib.patch
    - 0002-Fix-Python-3.4-undefined-symbol-clock_gettime.patch

build:
  number: 0
  skip: True  # [win or osx]
  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

requirements:
  build:
    - python
    - swig
    - git
    - pip
    - gcc
    - protobuf
    - numpy >=1.10.1
    - six >=1.10.0
    - wheel
    # - cudatoolkit
  run:
    - python
    - libgcc
    - protobuf
    - numpy >=1.10.1
    - six >=1.10.0
    # - cudatoolkit

test:
  imports:
    - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow

extra:
  recipe-maintainers:
    - jjhelmus
    - danielfrg
